using MahApps.Metro.Controls;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace JustAnotherCalculator
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : MetroWindow
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void DataGrid_AutoGeneratedColumns(object sender, EventArgs e)
        {

            try
            {
                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "Input").FirstOrDefault().Width = 400;
            }
            catch (Exception) { }

            try
            {
                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "Result").FirstOrDefault().Width = 200;
            }
            catch (Exception) { }


            try
            {
                ((DataGrid)sender).Columns.Where(x => x.Header.ToString() == "Notes").FirstOrDefault().Width = 600;
            }
            catch (Exception) { }

        }
    }
}
